language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - scripts/runtest.py
  - if [[$TRAVIS_PYTHON_VERSION == 3.6]]; then travis-sphinx --branches=master build; fi

after_success:
  - if [[$TRAVIS_PYTHON_VERSION == 3.6]]; then travis-sphinx --branches=master deploy; fi
